<a href="https://colab.research.google.com/github/Kishoby/Final-Research/blob/Data-Preprocessing/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [9]:
path="/content/drive/MyDrive/Research/16 months.csv"
df=pd.read_csv(path)
df.head(5)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,5/16/2024 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,5/16/2024 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,5/16/2024 9:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,5/16/2024 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,5/16/2024 9:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

In [10]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100554 entries, 0 to 100553
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       100554 non-null  object
 1   location_name                 100554 non-null  object
 2   latitude                      100554 non-null  float64
 3   longitude                     100554 non-null  float64
 4   timezone                      100554 non-null  object
 5   last_updated_epoch            100554 non-null  int64
 6   last_updated                  100554 non-null  object
 7   temperature_celsius           100554 non-null  float64
 8   temperature_fahrenheit        100554 non-null  float64
 9   condition_text                100554 non-null  object
 10  wind_mph                      100554 non-null  float64
 11  wind_kph                      100554 non-null  float64
 12  wind_degree                   100554 non-null  int64
 13  wind_direction                100554 non-null  object
 14  pressure_mb                   100554 non-null  int64
 15  pressure_in                   100554 non-null  float64
 16  precip_mm                     100554 non-null  float64
 17  precip_in                     100554 non-null  float64
 18  humidity                      100554 non-null  int64
 19  cloud                         100554 non-null  int64
 20  feels_like_celsius            100554 non-null  float64
 21  feels_like_fahrenheit         100554 non-null  float64
 22  visibility_km                 100554 non-null  float64
 23  visibility_miles              100554 non-null  int64
 24  uv_index                      100554 non-null  float64
 25  gust_mph                      100554 non-null  float64
 26  gust_kph                      100554 non-null  float64
 27  air_quality_Carbon_Monoxide   100554 non-null  float64
 28  air_quality_Ozone             100554 non-null  float64
 29  air_quality_Nitrogen_dioxide  100554 non-null  float64
 30  air_quality_Sulphur_dioxide   100554 non-null  float64
 31  air_quality_PM2.5             100554 non-null  float64
 32  air_quality_PM10              100554 non-null  float64
 33  air_quality_us-epa-index      100554 non-null  int64
 34  air_quality_gb-defra-index    100554 non-null  int64
 35  sunrise                       100554 non-null  object
 36  sunset                        100554 non-null  object
 37  moonrise                      100554 non-null  object
 38  moonset                       100554 non-null  object
 39  moon_phase                    100554 non-null  object
 40  moon_illumination             100554 non-null  int64
dtypes: float64(21), int64(9), object(11)
memory usage: 31.5+ MB

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,100554.000000,100554.000000,1.005540e+05,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,...,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000,100554.000000
mean,19.153462,22.091240,1.738234e+09,22.735669,72.925959,8.210337,13.216624,170.872288,1014.013625,29.943161,...,18.475274,511.003551,62.303738,15.732626,11.150693,25.854631,52.955739,1.750224,2.735794,50.507071
std,24.452766,65.814333,1.292005e+07,8.863278,15.953713,7.804832,12.558194,102.757199,11.264338,0.332589,...,14.566397,835.629636,32.087816,25.840596,40.243948,40.376942,162.199306,0.976633,2.551263,35.006080
min,-41.300000,-175.200000,1.715849e+09,-24.900000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.727085e+09,18.100000,64.600000,4.000000,6.500000,83.000000,1010.000000,29.830000,...,10.400000,233.700000,42.000000,1.300000,0.900000,7.400000,10.730000,1.000000,1.000000,16.000000
50%,17.250000,23.316700,1.738232e+09,24.800000,76.700000,6.900000,11.200000,165.000000,1013.000000,29.920000,...,15.700000,323.750000,59.000000,4.995000,2.405000,14.985000,21.830000,1.000000,2.000000,51.000000
75%,40.400000,50.580000,1.749459e+09,28.300000,82.900000,11.200000,18.000000,256.000000,1018.000000,30.050000,...,24.400000,503.200000,79.000000,17.945000,9.065000,29.415000,45.140000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.760516e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [11]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

#  No Missing Values

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

# No duplicate values found